// Sounds an admin can pick for booking / message pushes (/admin/settings),
// chosen to suit the museum: calm, dignified and Kurdish where they can be.
//
// Android 8+ fixes a notification channel's sound when the channel is
// created, so every sound gets its own channel and the server posts to the
// one matching system_settings.notification_sound. "default" keeps the
// original admin_alerts channel MainActivity creates natively; the others
// are created by NativePushBridge. The custom sounds live in the APK's
// res/raw and, for in-browser previews, in public/sounds — both generated by
// scripts/generate-notification-sounds.mjs.

export const NOTIFICATION_SOUNDS = [
  { id: "default", label: "ئاوازی سیستەم", description: "دەنگی بنەڕەتی ئاگادارکردنەوەی مۆبایلەکە" },
  { id: "gallery", label: "زەنگی هۆڵ", description: "سێ نۆتی نەرم، وەک بانگەوازی ناو هۆڵی مۆزەخانە" },
  { id: "santur", label: "سەنتوور", description: "ئاوازێکی کورتی کوردی لەسەر سەنتوور" },
  { id: "bronze", label: "زەنگی برۆنز", description: "یەک لێدانی ئارام بە دەنگدانەوەیەکی درێژ" },
  { id: "daf", label: "دەف", description: "ڕیتمی دەفی کوردی — زیندوو و ئاشکرا، بۆ ئەوەی لەدەستت نەچێت" },
] as const;

export type NotificationSoundId = (typeof NOTIFICATION_SOUNDS)[number]["id"];

export const DEFAULT_NOTIFICATION_SOUND: NotificationSoundId = "default";

export function isNotificationSound(v: unknown): v is NotificationSoundId {
  return NOTIFICATION_SOUNDS.some((s) => s.id === v);
}

export function soundChannelId(id: NotificationSoundId): string {
  return id === "default" ? "admin_alerts" : `admin_alerts_${id}`;
}

/** res/raw resource name — null for the phone's own default sound. */
export function soundResource(id: NotificationSoundId): string | null {
  return id === "default" ? null : `notify_${id}`;
}

export function soundPreviewUrl(id: NotificationSoundId): string | null {
  const res = soundResource(id);
  return res ? `/sounds/${res}.wav` : null;
}
