-- Create visitor_logs table for tracking website visits
CREATE TABLE IF NOT EXISTS visitor_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_url TEXT NOT NULL,
  ip_address TEXT,
  user_agent TEXT,
  device_type TEXT,
  visited_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE visitor_logs ENABLE ROW LEVEL SECURITY;

-- Allow public insert for tracking
CREATE POLICY "Allow public insert" ON visitor_logs
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

-- Allow authenticated users to view
CREATE POLICY "Allow authenticated select" ON visitor_logs
  FOR SELECT TO authenticated
  USING (true);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_visitor_logs_visited_at ON visitor_logs(visited_at DESC);
CREATE INDEX IF NOT EXISTS idx_visitor_logs_page_url ON visitor_logs(page_url);
