"use client";

import type { MotionValue } from "framer-motion";

interface PaintCanvasProps {
  progress: MotionValue<number>;
}

// The site's deep-red accent — same shade as the timeline dots/line
// elsewhere (e.g. HeroLogoStrip.tsx's ACCENT) — solid, not tinted.
const ACCENT = "#850B10";

// Five thin, wavy lines running bottom-left to top-right (a 1000x1000 square
// space, sliced to fill the viewport — see the svg's viewBox/
// preserveAspectRatio below — so the diagonal stays a true 45°, not skewed
// by the screen's aspect ratio). Each `d` starts at its bottom-left end and
// ends at its top-right end — that start->end direction is what
// .paint-line's stroke-dashoffset animation (globals.css) flows along.
// Each is a smooth sine-ish wave through a handful of points, generated by
// offsetting points along the diagonal perpendicular to it; b is the base
// line, the rest are the same wave shifted further to either side (a/c one
// step out, d/e two steps out) so they read as parallel strands rather than
// one thick line.
const LINES = [
  {
    variant: "d",
    d: "M -323,757 Q -67,599 -33,467 Q 1,335 109,276 Q 217,217 325,158 Q 433,99 467,-33 Q 501,-165 757,-323",
  },
  {
    variant: "a",
    d: "M -141,859 Q 75,741 109,609 Q 143,477 251,418 Q 359,359 467,300 Q 575,241 609,109 Q 643,-23 859,-141",
  },
  {
    variant: "b",
    d: "M -40,1040 Q 216,882 250,750 Q 284,618 392,559 Q 500,500 608,441 Q 716,382 750,250 Q 784,118 1040,-40",
  },
  {
    variant: "c",
    d: "M 141,1141 Q 357,1023 391,891 Q 425,759 533,700 Q 641,641 749,582 Q 857,523 891,391 Q 925,259 1141,141",
  },
  {
    variant: "e",
    d: "M 243,1323 Q 499,1165 533,1033 Q 567,901 675,842 Q 783,783 891,724 Q 999,665 1033,533 Q 1067,401 1323,243",
  },
] as const;

/**
 * A fixed, full-viewport background layer behind the whole page: the canvas
 * color and its faint grain texture, plus five thin wavy lines running
 * diagonally from the bottom-left to the top-right corner, each flowing
 * continuously in that direction on an infinite loop (see .paint-line in
 * globals.css). `progress` (the page's scroll fraction, from
 * ScrollExperience's useScroll()) isn't used here; the prop stays on the
 * signature so callers don't need to change if a scroll-linked effect is
 * added back later.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars -- progress kept on the signature, see comment above
export function PaintCanvas(_props: PaintCanvasProps) {
  return (
    <div aria-hidden className="pointer-events-none fixed inset-0 -z-10 overflow-hidden bg-canvas">
      <div className="absolute inset-0 bg-canvas-grain" />

      <svg
        className="absolute inset-0 h-full w-full"
        viewBox="0 0 1000 1000"
        preserveAspectRatio="xMidYMid slice"
        fill="none"
      >
        {LINES.map(({ variant, d }) => (
          <path
            key={variant}
            className={`paint-line paint-line--${variant}`}
            d={d}
            stroke={ACCENT}
            strokeWidth={2}
            strokeLinecap="round"
            strokeOpacity={0.03}
          />
        ))}
      </svg>
    </div>
  );
}
