"use client";

import { useEffect, useState } from "react";
import { useReducedMotion } from "framer-motion";
import { usePathname } from "next/navigation";
import { proxiedImage } from "@/lib/proxiedImage";

interface PaintCanvasProps {
  /** Background piece URLs, in order: site_profile.background_image_urls,
   * or the shipped set (backgroundDefaults.ts) until an admin saves one. */
  pieces: string[];
}

// The site's deep-red accent — same shade as the timeline dots/line
// elsewhere (e.g. HeroLogoStrip.tsx's ACCENT) — solid, not tinted.
const ACCENT = "#850B10";

// Five thin, wavy lines running bottom-left to top-right (a 1000x1000 square
// space, sliced to fill the viewport — see the svg's viewBox/
// preserveAspectRatio below — so the diagonal stays a true 45°, not skewed
// by the screen's aspect ratio). Each `d` starts at its bottom-left end and
// ends at its top-right end — that start->end direction is what
// .paint-line's stroke-dashoffset animation (globals.css) flows along.
// Each is a smooth sine-ish wave through a handful of points, generated by
// offsetting points along the diagonal perpendicular to it; b is the base
// line, the rest are the same wave shifted further to either side (a/c one
// step out, d/e two steps out) so they read as parallel strands rather than
// one thick line.
const LINES = [
  {
    variant: "d",
    d: "M -323,757 Q -67,599 -33,467 Q 1,335 109,276 Q 217,217 325,158 Q 433,99 467,-33 Q 501,-165 757,-323",
  },
  {
    variant: "a",
    d: "M -141,859 Q 75,741 109,609 Q 143,477 251,418 Q 359,359 467,300 Q 575,241 609,109 Q 643,-23 859,-141",
  },
  {
    variant: "b",
    d: "M -40,1040 Q 216,882 250,750 Q 284,618 392,559 Q 500,500 608,441 Q 716,382 750,250 Q 784,118 1040,-40",
  },
  {
    variant: "c",
    d: "M 141,1141 Q 357,1023 391,891 Q 425,759 533,700 Q 641,641 749,582 Q 857,523 891,391 Q 925,259 1141,141",
  },
  {
    variant: "e",
    d: "M 243,1323 Q 499,1165 533,1033 Q 567,901 675,842 Q 783,783 891,724 Q 999,665 1033,533 Q 1067,401 1323,243",
  },
] as const;

// Seconds each piece holds its slot. The two slots take turns changing, half
// this apart; .bg-piece's opacity transition (globals.css) does the fade.
const PIECE_SECONDS = 7;

// Each slot's box scales with the screen: 22% of its width / 34% of its
// height, never smaller than ~9rem × 10rem (phones) or bigger than
// 24rem × 26rem (large monitors). A piece fits inside at its own aspect
// ratio, so whichever side runs out first sets its size. Fainter on phones,
// where the text runs edge to edge over the pieces.
const SLOT_SIZE =
  "h-[clamp(10rem,34vh,26rem)] w-[clamp(9rem,22vw,24rem)] opacity-[0.08] md:opacity-[0.14]";

const SLOTS = [
  // Bottom-left.
  { className: `bottom-[6vh] left-[3vw] ${SLOT_SIZE}`, imgClassName: "bottom-0 left-0" },
  // Top-right.
  { className: `top-[16vh] right-[3vw] ${SLOT_SIZE}`, imgClassName: "top-0 right-0" },
] as const;

/**
 * The piece each slot shows at `tick` (one tick per half turn): the slots
 * change on alternate ticks, the second running half the list ahead, so with
 * 3+ pieces they never show the same one at once. One piece leaves the second
 * slot empty; two sit still, one per slot.
 */
function slotPieces(tick: number, count: number): [number, number | null] {
  if (count === 1) return [0, null];
  if (count === 2) return [0, 1];
  const ahead = Math.floor(count / 2);
  return [Math.floor(tick / 2) % count, (Math.floor((tick + 1) / 2) + ahead) % count];
}

// Uploaded pieces live in Supabase storage, so route them through Next's
// image endpoint (same-origin and resized, see proxiedImage); the shipped
// ones are already small local WebPs.
function pieceSrc(url: string) {
  return url.startsWith("/") ? url : proxiedImage(url, 640);
}

// Paths where the pieces fade out: the homepage's gallery and contact
// sections (HomeSectionUrlSync swaps the address bar to /ku/gallery etc. as
// they scroll into view, and usePathname follows it) and the standalone
// /contact page, which shares that URL.
const NO_PIECES_PATH = /^\/[^/]+\/(gallery|contact)$/;

/**
 * A fixed, full-viewport background layer behind the whole page: the canvas
 * color and its faint grain texture, faded museum pieces slowly cross-fading
 * in two corners (see SLOTS/slotPieces above), plus five thin wavy lines
 * running diagonally from the bottom-left to the top-right corner, each
 * flowing continuously in that direction on an infinite loop (see .paint-line
 * in globals.css). Reduced-motion visitors get the pieces held still.
 */
export function PaintCanvas({ pieces }: PaintCanvasProps) {
  const hidePieces = NO_PIECES_PATH.test(usePathname());
  const reduceMotion = useReducedMotion();
  const [tick, setTick] = useState(0);

  useEffect(() => {
    if (reduceMotion || pieces.length < 3) return;
    const id = setInterval(() => setTick((t) => t + 1), (PIECE_SECONDS / 2) * 1000);
    return () => clearInterval(id);
  }, [reduceMotion, pieces.length]);

  const shown = slotPieces(tick, pieces.length);

  return (
    <div aria-hidden className="pointer-events-none fixed inset-0 -z-10 overflow-hidden bg-canvas">
      <div className="absolute inset-0 bg-canvas-grain" />

      {pieces.length > 0 && (
        <div
          className={`absolute inset-0 transition-opacity duration-700 ${hidePieces ? "opacity-0" : "opacity-100"}`}
        >
          {SLOTS.map((slot, s) =>
            shown[s] === null ? null : (
              <div key={slot.imgClassName} className={`absolute ${slot.className}`}>
                {pieces.map((url, i) => (
                  // eslint-disable-next-line @next/next/no-img-element -- fixed decorative layer; next/image's layout modes don't fit a corner-anchored, content-sized box
                  <img
                    key={`${i}-${url}`}
                    src={pieceSrc(url)}
                    alt=""
                    decoding="async"
                    fetchPriority="low"
                    className={`bg-piece absolute max-h-full max-w-full ${slot.imgClassName} ${
                      i === shown[s] ? "opacity-100" : "opacity-0"
                    }`}
                  />
                ))}
              </div>
            )
          )}
        </div>
      )}

      <svg
        className="absolute inset-0 h-full w-full"
        viewBox="0 0 1000 1000"
        preserveAspectRatio="xMidYMid slice"
        fill="none"
      >
        {LINES.map(({ variant, d }) => (
          <path
            key={variant}
            className={`paint-line paint-line--${variant}`}
            d={d}
            stroke={ACCENT}
            strokeWidth={8}
            strokeLinecap="round"
            strokeOpacity={0.03}
          />
        ))}
      </svg>
    </div>
  );
}
